# Generated by Django 3.2.7 on 2021-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20211020_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
